type PlaylistType = {
  title: string;
  imageUrl: any;
  category: 'Playlist' | 'Álbum';
  author?: string;
  songCount?: number;
  autoGenerated?: boolean;
  isPinned?: boolean;
  isDownloaded?: boolean;
}

export default PlaylistType;