import PlaylistType from './../../types/PlaylistType';
import MixType from './../../types/MixType';
import { CircleArrowDownSolidIcon, ExtraInformation, PinSolidIcon, PlaylistDataContainer, PlaylistDetails, PlaylistImage, PlaylistItemListContainer, PlaylistTitle } from './styles';

type PlaylistItemListProps = {
  playlist: PlaylistType;
}

const PlaylistItemList: React.FC<PlaylistItemListProps> = ({
  playlist: {
    title,
    imageUrl,
    category,
    author,
    songCount,
    autoGenerated,
    isPinned,
    isDownloaded
  }
}) => {

  return (
    <PlaylistItemListContainer>
      <PlaylistImage source={imageUrl} />

      <PlaylistDataContainer>
        <PlaylistTitle>{title}</PlaylistTitle>
        <PlaylistDetails>
          {isPinned && <PinSolidIcon />}
          {isDownloaded && <CircleArrowDownSolidIcon />}
          <ExtraInformation>
            {category} • {autoGenerated ? 'Feita para Matheusinho' : (author ? author : `${songCount} músicas`)}
          </ExtraInformation>
        </PlaylistDetails>
      </PlaylistDataContainer>
    </PlaylistItemListContainer>
  );
}

export default PlaylistItemList;