import { useContext } from 'react';
import Theme from './../../stylesheets/theme';
import PlaylistType from './../../types/PlaylistType';
import { CircleArrowDownSolidIcon, ExtraInformation, PinSolidIcon, PlaylistDataContainer, PlaylistDetails, PlaylistImage, PlaylistItemListContainer, PlaylistTitle } from './styles';
import { UserContext } from '../../context/UserContext';

type PlaylistItemListProps = {
  playlist: PlaylistType;
  isPlaying?: boolean;
}

const PlaylistItemList: React.FC<PlaylistItemListProps> = ({
  playlist: {
    title,
    imageUrl,
    category,
    author,
    songCount,
    autoGenerated,
    isPinned,
    isDownloaded
  },
  isPlaying
}) => {
  const { userName } = useContext(UserContext);

  return (
    <PlaylistItemListContainer>
      <PlaylistImage source={imageUrl} />

      <PlaylistDataContainer>
        <PlaylistTitle style={isPlaying ? { color: Theme.colors.green } : {}}>{title}</PlaylistTitle>
        <PlaylistDetails>
          {isPinned && <PinSolidIcon />}
          {isDownloaded && <CircleArrowDownSolidIcon />}
          <ExtraInformation>
            {category} • {autoGenerated ? `Feita para ${userName}` : (
              author ? author : `${songCount} músicas`
            )}
          </ExtraInformation>
        </PlaylistDetails>
      </PlaylistDataContainer>
    </PlaylistItemListContainer>
  );
}

export default PlaylistItemList;